# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback
import globals
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import db
import lib

class Form(object):

    def eventBtn(self):
        dbu = db.DB()

        dict = {
            "id": self.edit_id.text(),
            "pw": self.edit_pw.text()
        }
        try:
            user = dbu.dictSelect("users", dict)

        except:
            traceback.print_exc()

        if (user):
            globals.user = user
            dick = {
                "u_id" : str(globals.user['_id'])
            }
            characters = dbu.dictSelect("characters",dick,"",True)
            globals.characters = characters

            self.Form.hide()
            self.main.setupData()
            self.Form2.show()
        else:
            lib.alert("회원정보가 틀립니다.")


    def setupUi(self, Form,Form2,main):
        self.main = main
        self.Form = Form
        self.Form2 = Form2
        Form.setObjectName("Form")
        Form.resize(400, 201)
        self.edit_id = QtWidgets.QLineEdit(Form)
        self.edit_id.setGeometry(QtCore.QRect(110, 60, 151, 31))
        self.edit_id.setObjectName("edit_id")
        self.edit_pw = QtWidgets.QLineEdit(Form)
        self.edit_pw.setGeometry(QtCore.QRect(110, 100, 151, 31))
        self.edit_pw.setObjectName("edit_pw")
        self.edit_pw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_id = QtWidgets.QLabel(Form)
        self.label_id.setGeometry(QtCore.QRect(30, 60, 71, 31))
        self.label_id.setObjectName("label_id")
        self.label_pw = QtWidgets.QLabel(Form)
        self.label_pw.setGeometry(QtCore.QRect(30, 100, 71, 31))
        self.label_pw.setObjectName("label_pw")
        self.btn_login = QtWidgets.QPushButton(Form)
        self.btn_login.setGeometry(QtCore.QRect(280, 60, 75, 71))
        self.btn_login.setObjectName("btn_login")

        self.btn_login.clicked.connect(self.eventBtn)


        self.retranslateUi(Form)


        QtCore.QMetaObject.connectSlotsByName(Form)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_id.setText(_translate("Form", "ID"))
        self.label_pw.setText(_translate("Form", "PW"))
        self.btn_login.setText(_translate("Form", "Login"))





if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
